version: '3'
services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: 
      context: requirement/mariadb
      dockerfile: dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: requirement/wordpress
      dockerfile: dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"
volumes:
  wordpress:
    driver: local 
    driver_opts:
    type: 'none' 									
    o: 'bind'
    device: '/Users/enja/Desktop/data/wordpress'	
  mariadb:
    driver: local
    driver_opts:
    type: 'none' 
    o: 'bind'
    device: '/Users/enja/Desktop/data/mariadb'
networks:
  inception:
    driver: bridge