version: '3'
services:
  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    expose:
      - "3306"
  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    healthcheck:       
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:3306 || exit 1"]       
      interval: 30s       
      timeout: 10s       
      retries: 3       
      start_period: 60s  
    restart: always
    expose:
      - "9000"
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aminux/Desktop/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aminux/Desktop/data/mariadb
networks:
  inception:
    driver: bridge