version: '3'
services:
  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/enja/Desktop/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/enja/Desktop/data/mariadb
networks:
  inception:
    driver: bridge